- merged reinstall.sh

diff --git a/pkg_update b/pkg_update
--- a/pkg_update
+++ b/pkg_update
@@ -926,8 +926,8 @@ update_origin() {
 make_version_list() {
 	if test ! -s "${cache}"
 	then
-		echo pkg_version -v -L 
-		pkg_version -v -L = | grep -v bsdpan- > "${cache}"
+		echo "pkg_version -v -L ="
+		pkg_version -v -L = /dev/null | grep -v bsdpan- > "${cache}"
 	fi
 }
 #
@@ -958,6 +958,10 @@ fix_moved_ports() {
 	fi
 }
 #
+# generate orderd list to deinstall all old packages on a host
+make_deinstall_list() {
+}
+#
 # inform usage
 usage() {
 	echo "Usage:" >&2
@@ -970,7 +974,11 @@ usage() {
 	echo "    ${0##*/}: dependency-update" >&2
 	echo "    ${0##*/}: fix-moved-ports" >&2
 	echo "    ${0##*/}: list-installed-ports" >&2
-	echo "    ${0##*/}: version-list" >&2
+	echo "    ${0##*/}: show-version-list" >&2
+	echo "    ${0##*/}: make-version-list" >&2
+	echo "    ${0##*/}: make-deinstall-list" >&2
+	echo "    ${0##*/}: reinstall" >&2
+	echo "    ${0##*/}: clean" >&2
 	echo "    ${0##*/}: check-installed-ports [port]" >&2
 	echo "    ${0##*/}: cvsup" >&2
 	echo "    ${0##*/}: full-update-jail [retry]" >&2
@@ -990,6 +998,8 @@ logdir="${PKG_UPDATE_LOGDIR:-${localdir}/log-${hostnames}}"
 hostname=`hostname`
 depends="${localdir}/data/depends.$(hostname)"
 cache="${localdir}/version-list.${hostname}"
+deinstall="${localdir}/deinstall.${hostname}"
+easyupdate="${localdir}/easyupdate.${hostname}"
 #
 #	get all path information from /etc/make.conf
 nowarn="COMMENT=0 CATEGORIES=0 PORTVERSION=0"
@@ -1132,8 +1142,23 @@ list-installed-ports)
 	shift
 	pkg_info -qao "${@}"
 	;;
-version-list)
+show-version-list)
 	make_version_list
+	;;
+make-version-list)
+	rm -f "${cache}"
+	make_version_list
+	;;
+make-deinstall-list)
+	make_deinstall_list
+	;;
+reinstall)
+	exec /bin/sh "${0}" install-packages "${deinstall}"
+	echo "error in path: ${0}" >&2
+	exit 64
+	;;
+clean)
+	rm -f "${cache}" "${deinstall}" "${easyupdate}"
 	;;
 check-installed-ports)
 	tmp1="/tmp/check-listed.$$"
