- usage more readable

diff --git a/pkg_update b/pkg_update
--- a/pkg_update
+++ b/pkg_update
@@ -956,18 +956,19 @@ fix_moved_ports() {
 #
 # inform usage
 usage() {
-	echo "Usage: ${0##*/}: make-packages [port] [...]" >&2
-	echo "Usage: ${0##*/}: add-packages [port] [...]" >&2
-	echo "Usage: ${0##*/}: install-packages [port] [...]" >&2
-	echo "Usage: ${0##*/}: clean-packages" >&2
-	echo "Usage: ${0##*/}: clean-distfiles" >&2
-	echo "Usage: ${0##*/}: fetch-distfiles" >&2
-	echo "Usage: ${0##*/}: dependency-update" >&2
-	echo "Usage: ${0##*/}: fix-moved-ports" >&2
-	echo "Usage: ${0##*/}: list-installed-ports" >&2
-	echo "Usage: ${0##*/}: check-installed-ports [port]" >&2
-	echo "Usage: ${0##*/}: cvsup" >&2
-	echo "Usage: ${0##*/}: full-update-jail [retry]" >&2
+	echo "Usage:" >&2
+	echo "    ${0##*/}: make-packages [port] [...]" >&2
+	echo "    ${0##*/}: add-packages [port] [...]" >&2
+	echo "    ${0##*/}: install-packages [port] [...]" >&2
+	echo "    ${0##*/}: clean-packages" >&2
+	echo "    ${0##*/}: clean-distfiles" >&2
+	echo "    ${0##*/}: fetch-distfiles" >&2
+	echo "    ${0##*/}: dependency-update" >&2
+	echo "    ${0##*/}: fix-moved-ports" >&2
+	echo "    ${0##*/}: list-installed-ports" >&2
+	echo "    ${0##*/}: check-installed-ports [port]" >&2
+	echo "    ${0##*/}: cvsup" >&2
+	echo "    ${0##*/}: full-update-jail [retry]" >&2
 	exit 64
 }
 
