- redesign show-missing, show-packages

diff --git a/pkg_update b/pkg_update
--- a/pkg_update
+++ b/pkg_update
@@ -140,7 +140,7 @@ port_uptodate() {
 			echo "# WARNING: using ${base}"
 		fi
 		echo "## ${base}: port_uptodate $1 "
-		bname=`make package-name`
+		bname=`make -V PKGNAME`
 		dir=`make -V PORTDIRNAME`
 		pkgfile=`make -V PKGFILE`
 		name="${bname}"
@@ -193,7 +193,7 @@ port_uptodate() {
 			continue
 		fi
 		log=`echo "${dir}" | sed -e 's=/=,=g'`
-		name=`cd ${fulldir} && make package-name`
+		name=`cd ${fulldir} && make -V PKGNAME`
 		if test -e ${pkg_dbdir}/${name}/+CONTENTS
 		then
 			echo "#installed:	${name} from ${dir}${for}"
@@ -510,7 +510,7 @@ add_packages_in_dir() {
 	err="${?}"
 	case "${err}" in
 	0)
-		name="$(make package-name)"
+		name=`make -V PKGNAME`
 		if test ! -e ${pkg_dbdir}/${name}/+CONTENTS
 		then
 			pkgfile="$(make -V PKGFILE)"
@@ -536,8 +536,8 @@ make_build_dirs() {
 	done
 }
 #
-# install the existing packages form a port to a host
-# Usage: add_packages_in_dir directory
+# install the existing packages from a port to a host
+# Usage: install_packages_in_dir directory
 install_packages_in_dir() {
 	dir="${1}"
 	if test "${dir}" = ""
@@ -562,7 +562,7 @@ install_packages_in_dir() {
 
 #	echo "# checking: ${dir}"
 	cd "${dir}" || return 69
-	name=`make package-name`
+	name=`make -V PKGNAME`
 	if test -e ${pkg_dbdir}/${name}/+CONTENTS
 	then
 		return
@@ -571,12 +571,89 @@ install_packages_in_dir() {
 	if test -f "${pkg_file}"
 	then
 		echo "pkg_add ${pkg_file}"
-		case "${2}" in
-		show)
-			return
-			;;
-		esac
 		pkg_add "${pkg_file}"
+		return
+	fi
+	echo "## package does not exist: ${pkg_file}"
+	echo "(cd ${dir} && make package)"
+}
+#
+# show the existing packages from a port to a host
+# Usage: show_packages_in_dir directory
+show_packages_in_dir() {
+	dir="${1}"
+	if test "${dir}" = ""
+	then
+		return
+	fi
+	case "${dir}" in
+	*nonexistant)
+		return
+		;;
+	esac
+	if test ! -d "${dir}"
+	then
+		xdir="${portsdir}/${dir}"
+		if test ! -d "${xdir}"
+		then
+			echo "## dir does not exist: ${dir}"
+			return
+		fi
+		dir="${xdir}"
+	fi
+
+#	echo "# checking: ${dir}"
+	cd "${dir}" || return 69
+	name=`make -V PKGNAME`
+	if test -e ${pkg_dbdir}/${name}/+CONTENTS
+	then
+		return
+	fi
+	pkg_file="$(make -V PKGFILE)"
+	if test -f "${pkg_file}"
+	then
+		echo "pkg_add ${pkg_file}"
+		return
+	fi
+	echo "## package does not exist: ${pkg_file}"
+	echo "(cd ${dir} && make package)"
+}
+#
+#
+# show the existing packages from a port to a host
+# Usage: show_missing_packages_in_dir directory
+show_missing_packages_in_dir() {
+	dir="${1}"
+	if test "${dir}" = ""
+	then
+		return
+	fi
+	case "${dir}" in
+	*nonexistant)
+		return
+		;;
+	esac
+	if test ! -d "${dir}"
+	then
+		xdir="${portsdir}/${dir}"
+		if test ! -d "${xdir}"
+		then
+			echo "## dir does not exist: ${dir}"
+			return
+		fi
+		dir="${xdir}"
+	fi
+
+#	echo "# checking: ${dir}"
+	cd "${dir}" || return 69
+	name=`make -V PKGNAME`
+	if test -e ${pkg_dbdir}/${name}/+CONTENTS
+	then
+		return
+	fi
+	pkg_file="$(make -V PKGFILE)"
+	if test -f "${pkg_file}"
+	then
 		return
 	fi
 	echo "## package does not exist: ${pkg_file}"
@@ -903,7 +980,7 @@ update_origin() {
 	movedto=$(
 		fgrep "${origin}|" "${portsdir}/MOVED" |
 		tail -1 |
-		cut -f2 -d "|" )
+		cut -d "|" -f2 )
 	if test "${movedto}" = ""
 	then
 		fgrep "${origin}|" "${portsdir}/MOVED"
@@ -1014,6 +1091,7 @@ usage() {
 	echo "    ${0##*/}: make-packages [port] [...]" >&2
 	echo "    ${0##*/}: add-packages [port] [...]" >&2
 	echo "    ${0##*/}: install-packages [port] [...]" >&2
+	echo "    ${0##*/}: show-packages [port] [...]" >&2
 	echo "    ${0##*/}: clean-packages" >&2
 	echo "    ${0##*/}: clean-distfiles" >&2
 	echo "    ${0##*/}: fetch-distfiles" >&2
@@ -1022,7 +1100,10 @@ usage() {
 	echo "    ${0##*/}: list-installed-ports" >&2
 	echo "    ${0##*/}: show-version-list" >&2
 	echo "    ${0##*/}: make-version-list" >&2
-	echo "    ${0##*/}: make-deinstall-list" >&2
+	echo "    ${0##*/}: show-deinstall-list" >&2
+	echo "    ${0##*/}: show-missing-packages" >&2
+	echo "    ${0##*/}: show-missing-reinstall" >&2
+	echo "    ${0##*/}: show-missing-installed" >&2
 	echo "    ${0##*/}: reinstall" >&2
 	echo "    ${0##*/}: clean" >&2
 	echo "    ${0##*/}: check-installed-ports [port]" >&2
@@ -1138,6 +1219,58 @@ install-packages)
 		fi
 	done
 	;;
+show-packages)
+	shift
+	if test "${#}" -lt 1
+	then
+		defaultdata="data/install-packages.$(hostname)"
+		if test ! -f "${defaultdata}"
+		then
+			usage
+		fi
+		exec /bin/sh "${0}" show-packages "${defaultdata}"
+		echo "error in path: ${0}" >&2
+		exit 64
+	fi
+	for i in "${@}"
+	do
+		if test -f "${i}"
+		then
+			for dir in `grep -v "^#" "${i}"`
+			do
+				show_packages_in_dir "${dir}"
+			done
+		else
+			show_packages_in_dir "${i}"
+		fi
+	done
+	;;
+show-missing-packages)
+	shift
+	if test "${#}" -lt 1
+	then
+		defaultdata="data/install-packages.$(hostname)"
+		if test ! -f "${defaultdata}"
+		then
+			usage
+		fi
+		exec /bin/sh "${0}" show-packages "${defaultdata}"
+		echo "error in path: ${0}" >&2
+		exit 64
+	fi
+	for i in "${@}"
+	do
+		if test -f "${i}"
+		then
+			for dir in `grep -v "^#" "${i}"`
+			do
+				show_missing_packages_in_dir "${dir}"
+			done
+		else
+			show_missing_packages_in_dir "${i}"
+		fi
+	done
+	;;
 fetch-distfiles)
 	shift
 	if test "${#}" -lt 1
@@ -1198,6 +1331,15 @@ make-version-list)
 make-deinstall-list)
 	make_version_list
 	make_deinstall_list
+	;;
+show-deinstall-list)
+	;;
+show-missing-reinstall)
+	/bin/sh "${0}" show-missing-packages `grep '^#.*[\010]' "${deinstall}" | cut -d "	" -f3`
+	;;
+show-missing-installed)
+	make_version_list
+	/bin/sh "${0}" show-missing-packages `pkg_info -qao`
 	;;
 reinstall)
 	exec /bin/sh "${0}" install-packages "${deinstall}"
