- fix warning after cvsup

diff --git a/pkg_update b/pkg_update
--- a/pkg_update
+++ b/pkg_update
@@ -1467,30 +1467,30 @@ make_easy_update() {
 # inform usage
 usage() {
 	echo "Usage:" >&2
-	echo "    ${0##*/}: make-packages [port] [...]" >&2
-	echo "    ${0##*/}: add-packages [port] [...]" >&2
-	echo "    ${0##*/}: install-packages [port] [...]" >&2
-	echo "    ${0##*/}: show-packages [port] [...]" >&2
-	echo "    ${0##*/}: show-missing-packages [port] [...]" >&2
-	echo "    ${0##*/}: clean-packages" >&2
-	echo "    ${0##*/}: clean-distfiles" >&2
-	echo "    ${0##*/}: fetch-distfiles" >&2
-	echo "    ${0##*/}: dependency-update" >&2
-	echo "    ${0##*/}: fix-moved-ports" >&2
-	echo "    ${0##*/}: list-installed-ports" >&2
-	echo "    ${0##*/}: show-version-list" >&2
-	echo "    ${0##*/}: make-version-list" >&2
-	echo "    ${0##*/}: make-deinstall-list" >&2
-	echo "    ${0##*/}: show-deinstall-list" >&2
-	echo "    ${0##*/}: show-missing-reinstall" >&2
-	echo "    ${0##*/}: show-missing-installed" >&2
-	echo "    ${0##*/}: reinstall" >&2
-	echo "    ${0##*/}: make-easy-update" >&2
-	echo "    ${0##*/}: replace-package [port] [...]" >&2
-	echo "    ${0##*/}: clean" >&2
-	echo "    ${0##*/}: check-installed-ports [port]" >&2
-	echo "    ${0##*/}: cvsup" >&2
-	echo "    ${0##*/}: full-update-jail [retry]" >&2
+	echo "    ${0##*/} make-packages [port] [...]" >&2
+	echo "    ${0##*/} add-packages [port] [...]" >&2
+	echo "    ${0##*/} install-packages [port] [...]" >&2
+	echo "    ${0##*/} show-packages [port] [...]" >&2
+	echo "    ${0##*/} show-missing-packages [port] [...]" >&2
+	echo "    ${0##*/} clean-packages" >&2
+	echo "    ${0##*/} clean-distfiles" >&2
+	echo "    ${0##*/} fetch-distfiles" >&2
+	echo "    ${0##*/} dependency-update" >&2
+	echo "    ${0##*/} fix-moved-ports" >&2
+	echo "    ${0##*/} list-installed-ports" >&2
+	echo "    ${0##*/} show-version-list" >&2
+	echo "    ${0##*/} make-version-list" >&2
+	echo "    ${0##*/} make-deinstall-list" >&2
+	echo "    ${0##*/} show-deinstall-list" >&2
+	echo "    ${0##*/} show-missing-reinstall" >&2
+	echo "    ${0##*/} show-missing-installed" >&2
+	echo "    ${0##*/} reinstall" >&2
+	echo "    ${0##*/} make-easy-update" >&2
+	echo "    ${0##*/} replace-package [port] [...]" >&2
+	echo "    ${0##*/} clean" >&2
+	echo "    ${0##*/} check-installed-ports [port]" >&2
+	echo "    ${0##*/} cvsup" >&2
+	echo "    ${0##*/} full-update-jail [retry]" >&2
 	exit 64
 }
 
@@ -1842,6 +1842,7 @@ cvsup)
 			fi
 		done
 	fi
+	shift
 	cd ${portsdir} && make update "$@"
 	;;
 full-update-jail)
